### ISSUE TITLE
Running status assumes data bytes are grouped in twos

### ISSUE THREAD

**Issue by rhofour** [newlandsvalley/elm-comidi#8]
I believe it's possible to have running status with something like Channel Aftertouch where you could get an odd number of data bytes.

**Comment by newlandsvalley** [comment]
This will complicate the parser a good deal unfortunately. It is straightforward to write a context-free parser where a given production is always parsed the same way irrespective of where it crops up.  But the manner in which we parse a running status message would have to depend on state (what the last 'real' message was).  It will need careful thought.

**Comment by rhofour** [comment]
I wasn't actually suggesting we add context. I think the right solution here is to just change Running Status so it always has a single int instead of two. I believe we could still parse it the same way, just parsing one byte instead of two.

Then, an app like elm-webmidi would be responsible for tracking the state and translating Running Status messages into something else.

I'm not a MIDI expert though, so I figured I'd double-check before making a backwards incompatible change like this.

**Comment by newlandsvalley** [comment]
I find the full spec very difficult to read, but here's a summary of channel voice messages -  https://www.csie.ntu.edu.tw/~r92092/ref/midi/midi_channel_voice.html.  It shows that NoteOn, NoteOff and Note Aftertouch (polyphonic key pressure) are all the same shape, whereas keyboard aftertouch (no note) is shorter.  I think this is the one you mean.

So, presumably we currently fail with keyboard aftertouch because the parser will consume the first int of the next event and thus blow up.  If we simply expected a single int, then parsing running status for NoteOn would likewise fail because it parses too little.

I think there is also virtue in tracking the state in the parser if we can manage to remember the 'daddy' event because we could then have the option of expanding the running status to a 'real' message in situ rather than post-processing it as we do now. 

(The issue is that you have to parse the expected number of bytes correctly in order to be ready for the next message that is _not_ a running status message. i.e. to test this properly in a round trip from a generator you need to generate a sequence of events, not just one.)

**Comment by rhofour** [comment]
So, I think the real-time and MIDI file cases should behave differently here. For real time use right now the Parser can't have any state since it gets separate calls for each message. We could change the API to have it return results and context or we can simply have it return Running Status with individual bytes and have the clients handling running status themselves. I think changing the API here to allow the parser to track this is probably the better way forward. It would also allow us to avoid exposing Running Status to clients. **What do you think?**

For parsing midi files tracking the state in the parser sounds perfectly reasonable and I don't see any reason we wouldn't want to do this. I can easily add some tests which use a sequence of events for this. In fact, it may be worthwhile to have a generator method which takes in a sequence of MIDI events and uses Running Status when possible.

**Comment by newlandsvalley** [comment]
Ah I begin to see what the issue is.  But for me, it's important that the midiEvent function is the same in both (file and generator) contexts.  Could we not change _parseMidiEvent_  and _midiEvent_ to something like this?

     parseMidiEvent : Maybe MidiEvent -> String -> Result.Result String MidiEvent

     midiEvent : Maybe MidiEvent -> Parser s MidiEvent

The idea being that this new _Maybe MidiEvent_ argument represents the 'parent' event context for any running status message.  As far as the generator is concerned, you would use _Just midiEvent_ as the context if you were issuing a running status message and _Nothing_ if not.  Surely the user of the generator must know the context for these messages?

I think I can _almost_ see a way of making use of this sort of approach when we're parsing files.  However, I'm not entirely confident yet about this - I'd need to play with it a bit first.

**Comment by rhofour** [comment]
I think it would require too much of the user to have them directly track the parent event themselves as it's a bit more complicated than just the last event as things like Real Time Category messages (0xF8 - 0xFF) do not break up running status.

However, I think we can do something very similar if we just leave the context opaque to the user. So we introduce a new type:

`MidiContext : Maybe MidiEvent`

Then we have the user track this and we update it ourselves:

`parseMidiEvent : Maybe MidiContext -> String -> Result.Result String (MidiEvent, MidiContext)`

That way we don't require the clients have any understanding of Running Status.

On the generate side I can Midi.Generate.event to look like:

`event : Maybe MidiContext -> MidiEvent -> (List Byte, MidiContext)`

For files I think we can leave the API completely unchanged. The parser will have to track context, but we never need to pass it on to the user since we get the whole file at once.

**Comment by newlandsvalley** [comment]
Still not convinced.  Can we move the discussion to slack?

**Comment by newlandsvalley** [comment]
I think this is relevant on page 92 of the spec:

> The receiver should always hold the last status byte in a Running Status buffer in case the transmitter is utilizing Running Status to reduce the number of bytes sent. This also means the receiver has to determine how many data bytes (one or two) are associated with each message. 

I think we can consider that the parser is a receiver. It then gives an algorithm for how it should behave and says:

> The data bytes are ignored when the value of the status buffer is 0 (zero).

which happens when there is no last status byte saved to the status buffer.  This defines the behaviour for live streams, but it does imply that some sort of 'live stream parser' needs to store state between messages.  How we do that, I'm not sure.

In the case of the file parser, we can follow this mechanism, I hope, if we save event state each time we parse an event and thus make the last status byte available to a subsequent running status event.

**Comment by rhofour** [comment]
Looks like Running Status output isn't supported by WebMidi.

From the [spec](https://webaudio.github.io/web-midi-api/#MIDIOutput):
> The data contains one or more valid, complete MIDI messages. Running status is not allowed in the data, as underlying systems may not support it.

Furthermore, looking at https://github.com/WebAudio/web-midi-api/issues/24 shows that we'll never receive running status messages from WebMidi either. This means that the midi event parser shouldn't need any context.

We'll still need it for parsing MIDI files however, but we can at least completely hide it from the user.

**Comment by newlandsvalley** [comment]
Excellent!  I can solve this for the file parser using bind (andThen) but unfortunately, in Elm / elm-combine, this is not stack-safe.  As you say, no longer an issue if we restrict event message parsing to events emanating from web-midi.

**Comment by newlandsvalley** [comment]
Fixed, I hope in the running-status branch - https://github.com/newlandsvalley/elm-comidi/tree/running-status.

**Comment by rhofour** [comment]
As far as running status is concerned the only thing I see is you forgot to delete MidiTypes.RunningStatus. As far as I can see it's not used anymore and it shouldn't be exposed.

I don't think the SysEx handling is quite right yet though. If I'm reading page 135 of the spec right we need to differentiate between SysEx events started with F0 and started with F7. When an event is started with F0 it means we should transmit an F0, but if an event is started with F7 we don't want to transmit that. The example on the next page shows this.

I think the easiest solution there would be to just include the F7 in the message if it starts with it, but not the F0. If we do this I think we'd want to be careful to specify that in the docs.

**Comment by newlandsvalley** [comment]
Good point about removing RunningStatus from MidiEvent.  This issue fixed by merging in the running-status branch - 6778be9387bf8d8bf1eb9afe4216c766c20e2c02.  Let's track SysEx progress in the issue dedicated to it,
